name: Security Checks

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Instalar Semgrep
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install semgrep

      - name: Verificar código com Semgrep
        run: semgrep --config "p/ci"

  owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Instalar OWASP ZAP
        run: sudo apt-get install zaproxy

      - name: Executar verificação com OWASP ZAP
        run: zap-baseline.py -t http://localhost:8000